name: Website Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
      
    - name: Azure Static Website
      uses: tibor19/static-website-deploy@v1
      with:
        # Connection String of the Azure Storage Container
        connection-string: 'DefaultEndpointsProtocol=https;AccountName=lawrenceharkness;AccountKey=oGWru/yLTu2ECQsr8GiqzzQWPgsXHoxuNHDbk6YVNaawZBM+t2E3mXGQVWAnIfkUA8k70FKwrj2RNFKiJNN6fA==;BlobEndpoint=https://lawrenceharkness.blob.core.windows.net/;QueueEndpoint=https://lawrenceharkness.queue.core.windows.net/;TableEndpoint=https://lawrenceharkness.table.core.windows.net/;FileEndpoint=https://lawrenceharkness.file.core.windows.net/; '
        # Name of the Blob Container Storage
        blob-container-name: '$web'


    
